### ISSUE TITLE
FormatTimeInMillisAsSeconds in gtest/src/gtest.cc:3504 causes compile errors when using conversion checking

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googlemock#173]
```
Using gcc 4.8.2 with option -Wconversion causes compile errors in the above 
source. Attached a patch.
```

Original issue reported on code.google.com by `ChristTh...@gmail.com` on 7 Mar 2015 at 3:57

Attachments:
- [patch](https://storage.googleapis.com/google-code-attachments/googlemock/issue-173/comment-0/patch)

**Comment by BillyDonahue** [comment]
This issue was moved to google/googletest#518
