### ISSUE TITLE
gmock git repository is of limited use without a gtest submodule

### ISSUE THREAD

**Issue by obruns** [google/googlemock#178]
[I had opened this issue as #181 at 2015-08-24 8:15 PM UTC but the project has been regenerated in the meantime; my considerations wrt. breaking existing users may not apply ;)]

Unit test frameworks are a prime example for Git submodules: You depend on the code, yet it is unlikely you'll ever change it. All you do is pulling in a newer version of the foreign code whenever you see the need for it - so why version the entire third party code when you can maintain just the SHA-1?

Unfortunately the above cannot be done with this gmock repository due to the unmet gtest dependency.
Ideally, at least the 1.7.0 tag (and all commits thereafter) have gtest added as a submodule. Yes, this means altering history but I think it is justified for the following reasons:
- the repo clone is less than a week old; the announcement on the mailing list has been made within the past 48 hours. Hence rewriting history won't break too many users
- making the submodule available to a long-time stable release (1.7.0) helps conservative users that would not jump to a 1.8.0 release anytime soon

Suggested procedure:
- take down the repository or add a warning about changes to the history
- rewrite the commit pointed to by the 1.7.0 tag so that the gtest/ subdirectory is a submodule
- test all commits since (and including) that 1.7.0 one
- re-create the 1.7.0 tag (--force)
- force-push the rewritten history

This would be the absolute minimum. Ideally, all 1.x tags would get such treatment (as time permits).

Related: #180 (lost when the project was regenerated; it illustrated how the unmet gtest dependency confuses users, similar to what Alex Shaver says on the mailing list (link below))
Related: https://groups.google.com/d/msg/googlemock/UD3nRr3RAQk/tj-R2A9UCAAJ

**Comment by BillyDonahue** [comment]
This issue was moved to google/googletest#513
